mod audit;
mod clones;
mod coverage;
mod cycles;
mod dead_code;
mod debt;
mod dependencies;
mod entry_points;
mod hot_paths;
mod manifests;
mod paths;
mod project_identity;
pub(super) mod runtime;
mod scc;

pub(super) use audit::audit;
pub(super) use clones::duplicates;
pub(super) use coverage::coverage;
pub(super) use cycles::runtime_dependency_cycles;
pub(super) use dead_code::dead_code;
pub(super) use hot_paths::hot_paths;
pub(super) use paths::{is_non_product, path_is_visible};
